[relaychain]
default_command = "{{POLKADOT_BINARY_PATH}}"
default_args = [ "-lparachain=debug,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace" ]
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice-validator"
	validator = true
	rpc_port = 9932
	ws_port = 9942
	extra_args = ["--no-mdns --bootnodes {{'bob-validator'|zombie('multiAddress')}}"]

	[[relaychain.nodes]]
	name = "bob-validator"
	validator = true
	rpc_port = 9933
	ws_port = 9943
	extra_args = ["--no-mdns --bootnodes {{'alice-validator'|zombie('multiAddress')}}"]

	[[relaychain.nodes]]
	name = "charlie-validator"
	validator = true
	rpc_port = 9934
	ws_port = 9944
	extra_args = ["--no-mdns --bootnodes {{'alice-validator'|zombie('multiAddress')}}"]

[[parachains]]
id = 1013
chain = "bridge-hub-rococo-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice-collator"
	validator = true
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
	rpc_port = 8933
	ws_port = 8943
	extra_args = [
		"-lparachain=debug,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace",
		"--force-authoring", "--no-mdns", "--bootnodes {{'bob-collator'|zombie('multiAddress')}}",
		"-- --port 41333 --rpc-port 48933 --ws-port 48943 --no-mdns", "--bootnodes {{'alice-validator'|zombie('multiAddress')}}"
	]

	# run bob as parachain collator
	[[parachains.collators]]
	name = "bob-collator"
	validator = true
	command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
	rpc_port = 8934
	ws_port = 8944
	extra_args = [
		"-lparachain=trace,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm::weight=trace,xcm::filter_asset_location=trace,xcm::send_xcm=trace,xcm::barriers=trace,xcm::barrier=trace,xcm::execute_xcm=trace,xcm::contains=trace,xcm::execute_xcm_in_credit,xcm::process_instruction=trace,xcm::currency_adapter=trace,xcm::origin_conversion=trace,xcm::fungibles_adapter=trace,xcm::process=trace,xcm::execute=trace",
		"--force-authoring", "--no-mdns", "--bootnodes {{'alice-collator'|zombie('multiAddress')}}",
		"-- --port 41334 --rpc-port 48934 --ws-port 48944 --no-mdns", "--bootnodes {{'bob-validator'|zombie('multiAddress')}}"
	]
